// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpSGCFb01pW2Kieck5D4d_r6WRHuunv7s',
    appId: '1:538523609367:web:49e185a5ce53ba71efaf52',
    messagingSenderId: '538523609367',
    projectId: 'testfirebase-ab7a2',
    authDomain: 'testfirebase-ab7a2.firebaseapp.com',
    databaseURL: 'https://testfirebase-ab7a2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testfirebase-ab7a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF49o1DnKAUoBcBAEIwKeDB1nZhbqPSBA',
    appId: '1:538523609367:android:9f1b6cd38ff13100efaf52',
    messagingSenderId: '538523609367',
    projectId: 'testfirebase-ab7a2',
    databaseURL: 'https://testfirebase-ab7a2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testfirebase-ab7a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Ts-w52TfR3DvLYdcD68VZapZBzTSKgU',
    appId: '1:538523609367:ios:df32f8747e10de36efaf52',
    messagingSenderId: '538523609367',
    projectId: 'testfirebase-ab7a2',
    databaseURL: 'https://testfirebase-ab7a2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testfirebase-ab7a2.firebasestorage.app',
    iosBundleId: 'com.example.informatiqueblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Ts-w52TfR3DvLYdcD68VZapZBzTSKgU',
    appId: '1:538523609367:ios:df32f8747e10de36efaf52',
    messagingSenderId: '538523609367',
    projectId: 'testfirebase-ab7a2',
    databaseURL: 'https://testfirebase-ab7a2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testfirebase-ab7a2.firebasestorage.app',
    iosBundleId: 'com.example.informatiqueblog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpSGCFb01pW2Kieck5D4d_r6WRHuunv7s',
    appId: '1:538523609367:web:7f74ebe62b47d014efaf52',
    messagingSenderId: '538523609367',
    projectId: 'testfirebase-ab7a2',
    authDomain: 'testfirebase-ab7a2.firebaseapp.com',
    databaseURL: 'https://testfirebase-ab7a2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testfirebase-ab7a2.firebasestorage.app',
  );
}
